# Copyright 2025 Columnar Technologies Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[workspace]
name = "dbc"
version = "0.1.0"
description = "Automations for the dbc project"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
python = ">=3.8"

[environments]
cdn = ["cdn"]
docs = ["docs"]

[feature.cdn.dependencies]
pyyaml = ">=6.0"
faker = ">=19.0.0"

[feature.cdn.tasks]
cdn-generate = "python scripts/cdn.py"
cdn-serve = "python -m http.server -d cdn-dev"

[feature.docs.pypi-dependencies]
mkdocs-material = { version = "*", extras = ["imaging"] }

[feature.docs.dependencies]
cairo = ">=1.18.4,<2"

[feature.docs.tasks]
docs-build = "mkdocs build"
docs-serve = "mkdocs serve"
