# Copyright 2026 Columnar Technologies Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Where to deploy to"
        required: true
        type: environment

      release_tag:
        description: "Tag of the GitHub release (example: v0.0.1)"
        required: true

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write # For AWS auth

jobs:
  deploy:
    name: "deploy ${{ inputs.environment }}"
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a  # v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: deploy-${{ inputs.environment }}-${{ github.run_id }}-${{ github.run_attempt }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Check role
        run: |
          aws sts get-caller-identity

      - name: Download release artifacts
        run: |
          gh release download ${{ inputs.release_tag }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload artifacts
        run: |
          aws s3 cp . s3://dbc-distribution/${{ inputs.release_tag }} --recursive
